site_name: whoiam Documentation
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    scheme: whoiam

extra_css:
  - stylesheets/palette.css

repo_url: https://github.com/cliwright/whoiam
repo_name: cliwright/whoiam

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Contributing: contributing.md
  - License: license.md
